// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtwL62eHfCyYGUbHpofp0daCIGE__p8uI',
    appId: '1:509021859724:web:7a9d0f7c492d72bbc7b0a9',
    messagingSenderId: '509021859724',
    projectId: 'naijameds',
    authDomain: 'naijameds.firebaseapp.com',
    storageBucket: 'naijameds.firebasestorage.app',
    measurementId: 'G-G10K805F8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAevHqc6GvDomhDR0cMkNuJsofla6hTfSY',
    appId: '1:509021859724:android:2f7cd04346f14777c7b0a9',
    messagingSenderId: '509021859724',
    projectId: 'naijameds',
    storageBucket: 'naijameds.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAH-N7A-pSwRLVDk_zfTWH4d0boHBUDw4',
    appId: '1:509021859724:ios:404d50686be79652c7b0a9',
    messagingSenderId: '509021859724',
    projectId: 'naijameds',
    storageBucket: 'naijameds.firebasestorage.app',
    iosBundleId: 'com.example.naijameds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAH-N7A-pSwRLVDk_zfTWH4d0boHBUDw4',
    appId: '1:509021859724:ios:404d50686be79652c7b0a9',
    messagingSenderId: '509021859724',
    projectId: 'naijameds',
    storageBucket: 'naijameds.firebasestorage.app',
    iosBundleId: 'com.example.naijameds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtwL62eHfCyYGUbHpofp0daCIGE__p8uI',
    appId: '1:509021859724:web:279247eddf9afa63c7b0a9',
    messagingSenderId: '509021859724',
    projectId: 'naijameds',
    authDomain: 'naijameds.firebaseapp.com',
    storageBucket: 'naijameds.firebasestorage.app',
    measurementId: 'G-EYXD6HKMNX',
  );
}